import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import { publicClient } from "@/lib/supabase";
export const revalidate = 300;
export default async function Methods() {
  const { data } = await publicClient().from("summary").select("value").eq("key", "methods_md").maybeSingle();
  const md = ((data?.value as any)?.text ?? "Methods have not been published yet. Run ingest/sync_outputs.py.").replace(/—/g, ", ").replace(/–/g, " to ");
  return (
    <div className="max-w-4xl">
      <div className="eyebrow">Methods</div>
      <h1 className="display serif text-[54px] mt-2">Show the math.</h1>
      <p className="text-[13.5px] text-[var(--ink-2)] mt-4 mb-6 leading-6">This page is generated by the detector code from the warehouse, so every number is reproducible from public files. It states what each evaluation can and cannot support, including where labels overlap the score.</p>
      <div className="card p-8 prose-methods"><ReactMarkdown remarkPlugins={[remarkGfm]}>{md}</ReactMarkdown></div>
    </div>
  );
}
