import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import { publicClient } from "@/lib/supabase";
export const revalidate = 300;
export default async function Methods() {
  const { data } = await publicClient().from("summary").select("value").eq("key", "methods_md").maybeSingle();
  const md = (data?.value as any)?.text ?? "Methods have not been published yet. Run ingest/sync_outputs.py.";
  return (
    <div className="max-w-4xl">
      <h1 className="serif text-[36px] leading-none mb-2">Methods</h1>
      <p className="text-[13px] text-[var(--ink-3)] mb-6">The full methods page is generated by the detector code from the warehouse, so every number here is reproducible from public files.</p>
      <div className="card bg-white p-8 prose-methods"><ReactMarkdown remarkPlugins={[remarkGfm]}>{md}</ReactMarkdown></div>
    </div>
  );
}
