import { money, ordinal, moneyExact } from "@/lib/labels";
type MCode = { hcpcs: string; description: string; paid: number; share: number; months: number; patient_months: number; dpm: number | null; dpm_pct: number | null; dpm_median: number | null; dpm_p95: number | null; high_vector: boolean; charge_ratio: number | null; peer_ratio_median: number | null; medicare_services: number | null };
type MedCode = { hcpcs: string; description: string; services: number; beneficiaries: number; paid: number; share: number; avg_submitted: number; avg_allowed: number; charge_ratio: number | null; peer_ratio_median: number | null; peer_ratio_p90: number | null };
const pct = (v: number | null | undefined) => (v == null ? "" : ordinal(v * 100));
export function Procedures({ medicaid, medicare, fallback }: { medicaid: MCode[]; medicare: MedCode[]; fallback?: { code: string; paid: number; months: number; role?: string }[] }) {
  if (!medicaid?.length && !medicare?.length && !fallback?.length) return null;
  return (
    <div className="card p-5">
      <h2 className="serif text-[24px] mb-1">Procedures billed</h2>
      <p className="text-[12.5px] text-[var(--ink-3)] mb-3">The specific codes behind the dollars. Medicaid figures come from T-MSIS (2018 to 2024) and are compared with every other provider billing the same code; Medicare figures come from the 2024 physician and supplier file and compare this provider's submitted charge with what Medicare allowed, against the usual ratio for that code.</p>
      {medicaid?.length ? <div className="overflow-x-auto"><div className="eyebrow mb-1">Medicaid, largest codes</div>
        <table className="table"><thead><tr><th>code</th><th>what it is</th><th>paid</th><th>share</th><th>per patient-month</th><th>typical</th><th>rank among providers</th><th></th></tr></thead>
          <tbody>{medicaid.map(c => <tr key={c.hcpcs}><td className="mono">{c.hcpcs}</td><td className="text-[12px] max-w-[300px]">{c.description || "Medicaid service code"}{c.high_vector ? <span className="tag tag-danger ml-2">history of abuse</span> : null}</td><td>{money(c.paid)}</td><td>{Math.round(c.share * 100)}%</td><td>{c.dpm != null ? moneyExact(c.dpm) : ""}</td><td className="text-[var(--ink-3)]">{c.dpm_median != null ? `${moneyExact(c.dpm_median)} (top 5% from ${moneyExact(c.dpm_p95)})` : ""}</td><td>{c.dpm_pct != null ? <span className={c.dpm_pct >= 0.95 ? "font-semibold" : ""}>{pct(c.dpm_pct)} percentile</span> : <span className="text-[var(--ink-3)]">too few months to rank</span>}</td><td className="w-[90px]"><div className="h-[6px] bg-[var(--paper-2)]"><div className="h-[6px]" style={{ width: `${Math.max(2, (c.dpm_pct ?? 0) * 100)}%`, background: (c.dpm_pct ?? 0) >= 0.95 ? "var(--blue)" : "#7f93ab" }} /></div></td></tr>)}</tbody></table></div> : null}
      {medicare?.length ? <div className="overflow-x-auto mt-5"><div className="eyebrow mb-1">Medicare Part B 2024, largest codes</div>
        <table className="table"><thead><tr><th>code</th><th>what it is</th><th>services</th><th>beneficiaries</th><th>paid</th><th>submitted per service</th><th>allowed per service</th><th>charge to allowed</th><th>usual for this code</th></tr></thead>
          <tbody>{medicare.map(c => { const hi = c.charge_ratio != null && c.peer_ratio_median != null && c.charge_ratio >= 3 * c.peer_ratio_median; return <tr key={c.hcpcs}><td className="mono">{c.hcpcs}</td><td className="text-[12px] max-w-[300px]">{c.description}</td><td>{Number(c.services).toLocaleString()}</td><td>{Number(c.beneficiaries).toLocaleString()}</td><td>{money(c.paid)}</td><td>{money(c.avg_submitted)}</td><td>{money(c.avg_allowed)}</td><td className={hi ? "font-semibold" : ""}>{c.charge_ratio != null ? `${c.charge_ratio.toFixed(1)}x` : ""}</td><td className="text-[var(--ink-3)]">{c.peer_ratio_median != null ? `${Number(c.peer_ratio_median).toFixed(1)}x (90th percentile ${Number(c.peer_ratio_p90).toFixed(1)}x)` : ""}</td></tr>; })}</tbody></table>
        <p className="text-[11px] text-[var(--ink-3)] mt-1">A submitted charge many times the allowed amount is common and lawful; it matters when it is far above what other providers submit for the same code.</p></div> : null}
      {!medicaid?.length && fallback?.length ? <div className="overflow-x-auto"><div className="eyebrow mb-1">Medicaid, largest codes</div><table className="table"><thead><tr><th>code</th><th>paid</th><th>months</th><th>role</th></tr></thead><tbody>{fallback.map(r => <tr key={r.code}><td className="mono">{r.code}</td><td>{money(r.paid)}</td><td>{r.months}</td><td>{r.role}</td></tr>)}</tbody></table></div> : null}
    </div>
  );
}
